### ISSUE TITLE
EmptyStackException when trying to export

### ISSUE THREAD

**Issue by MrMuskle** [FabricMC/Enigma#229] opened 2020-04-19 08:52 UTC
**Build:**
	[enigma-0.15.2+build.165-all.jar](https://maven.fabricmc.net/cuchaz/enigma/0.15.2%2Bbuild.165/enigma-0.15.2%2Bbuild.165-all.jar)

**Java Runtime Environment:**
	Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
	Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)

**Imported Java Archive:**
	[server.jar](https://launcher.mojang.com/v1/objects/754bbd654d8e6bd90cd7a1464a9e68a0624505dd/server.jar) – 20w16a

**Loaded ProGuard Mappings:**
	[server.txt](https://launcher.mojang.com/v1/objects/713d312463ed7186fff90ec72f922810ea8ad010/server.txt) – 20w16a

**Crash Log:**
	[enigma_crash.log](https://pastebin.com/raw/PuaKV9Jz)

**Comment by nathanowen42** [comment] 2020-05-09 09:08
I am also getting this issue.  I am running on Ubuntu, here are my logs:
[enigma_crash.log](https://github.com/FabricMC/Enigma/files/4603061/enigma_crash.log)

**Comment by Earthcomputer** [comment] 2020-05-09 09:11
That looks like a different crash log

**Comment by nathanowen42** [comment] 2020-05-11 15:51
Possibly, my java debug skills are a bit rusty.  Downgrading to  0.14.3 fixed my issue

**Comment by SkytAsul** [comment] 2020-05-15 20:36
Stacktrace with the latest build:
```
java.lang.Error: java.util.EmptyStackException
	at cuchaz.enigma.gui.dialog.ProgressDialog.lambda$0(ProgressDialog.java:72)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.EmptyStackException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at cuchaz.enigma.EnigmaProject.exportRemappedJar(EnigmaProject.java:172)
	at cuchaz.enigma.gui.GuiController.lambda$5(GuiController.java:211)
	at cuchaz.enigma.gui.dialog.ProgressDialog.lambda$0(ProgressDialog.java:68)
	... 1 more
Caused by: java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:102)
	at java.util.Stack.pop(Stack.java:84)
	at cuchaz.enigma.bytecode.translators.TranslationSignatureVisitor.visitInnerClassType(TranslationSignatureVisitor.java:30)
	at org.objectweb.asm.signature.SignatureReader.parseType(SignatureReader.java:198)
	at org.objectweb.asm.signature.SignatureReader.accept(SignatureReader.java:122)
	at cuchaz.enigma.translation.representation.Signature.remap(Signature.java:63)
	at cuchaz.enigma.translation.representation.Signature.translate(Signature.java:96)
	at cuchaz.enigma.translation.MappingTranslator.translate(MappingTranslator.java:22)
	at cuchaz.enigma.translation.representation.entry.ClassDefEntry.translate(ClassDefEntry.java:75)
	at cuchaz.enigma.translation.representation.entry.ClassDefEntry.translate(ClassDefEntry.java:1)
	at cuchaz.enigma.translation.representation.entry.ParentedEntry.translate(ParentedEntry.java:70)
	at cuchaz.enigma.translation.representation.entry.ParentedEntry.translate(ParentedEntry.java:1)
	at cuchaz.enigma.translation.MappingTranslator.translate(MappingTranslator.java:22)
	at cuchaz.enigma.translation.mapping.EntryRemapper.deobfuscate(EntryRemapper.java:75)
	at cuchaz.enigma.ProposingTranslator.translate(ProposingTranslator.java:29)
	at cuchaz.enigma.EnigmaProject.lambda$0(EnigmaProject.java:159)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
	at java.util.stream.AbstractTask.compute(AbstractTask.java:316)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
The class causing the bug : `it/unimi/dsi/fastutil/longs/Long2ObjectAVLTreeMap$Submap$SubmapEntryIterator`
The signature: `Lit/unimi/dsi/fastutil/longs/Long2ObjectAVLTreeMap<TV;>.Submap.SubmapIterator;Lit/unimi/dsi/fastutil/objects/ObjectListIterator<Lit/unimi/dsi/fastutil/longs/Long2ObjectMap$Entry<TV;>;>;`

**Comment by MrIvanPlays** [comment] 2020-05-19 06:05
Same problem

**Comment by 2xsaiko** [comment] 2020-06-07 13:38
Duplicate of #119

**Closed by 2xsaiko** 2020-06-07 13:38 UTC
Labels: bug, duplicate
