### ISSUE TITLE
Error when importing server jar "sizes don't match"

### ISSUE THREAD

**Issue by SkytAsul** [FabricMC/Enigma#179] opened 2019-11-12 18:28 UTC
When opening a server jar with the latest Enigma version (0.14.2.143), it crashes with this stack trace:
`java.lang.Error: java.lang.RuntimeException: org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 117: sizes don't match
	at cuchaz.enigma.gui.dialog.ProgressDialog.lambda$runOffThread$0(ProgressDialog.java:70)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 117: sizes don't match
	at cuchaz.enigma.analysis.index.IndexReferenceVisitor.lambda$visitMethod$0(IndexReferenceVisitor.java:49)
	at cuchaz.enigma.analysis.MethodNodeWithAction.visitEnd(MethodNodeWithAction.java:17)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1287)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:688)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
	at cuchaz.enigma.analysis.ClassCache.visit(ClassCache.java:108)
	at cuchaz.enigma.analysis.index.JarIndex.indexJar(JarIndex.java:67)
	at cuchaz.enigma.analysis.ClassCache.index(ClassCache.java:123)
	at cuchaz.enigma.Enigma.openJar(Enigma.java:55)
	at cuchaz.enigma.gui.GuiController.lambda$openJar$1(GuiController.java:90)
	at cuchaz.enigma.gui.dialog.ProgressDialog.lambda$runOffThread$0(ProgressDialog.java:66)
	... 1 more
Caused by: org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 117: sizes don't match
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:295)
	at cuchaz.enigma.analysis.index.IndexReferenceVisitor.lambda$visitMethod$0(IndexReferenceVisitor.java:47)
	... 11 more
Caused by: java.lang.IllegalStateException: sizes don't match
	at cuchaz.enigma.analysis.InterpreterPair.pair(InterpreterPair.java:100)
	at cuchaz.enigma.analysis.InterpreterPair.merge(InterpreterPair.java:88)
	at cuchaz.enigma.analysis.InterpreterPair.merge(InterpreterPair.java:14)
	at org.objectweb.asm.tree.analysis.Frame.merge(Frame.java:676)
	at org.objectweb.asm.tree.analysis.Analyzer.merge(Analyzer.java:541)
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:267)
	... 12 more
`
Any idea how to fix this problem?
The server jar is: https://launcher.mojang.com/v1/objects/0d0d7db69eb40408c23ce4503dfd00671bcb9e6b/server.jar

**Comment by liach** [comment] 2019-11-12 18:34
I had been able to reproduced the problem. For now, you can import the client jar or the merged jar from executing `gradle mergeJars` in yarn instead, given the client jar has everything that the server jar has (including all dedicated server classes etc.)

**Comment by SkytAsul** [comment] 2019-11-12 20:04
Well in fact I wanted to use Enigma to decompile, remap and save the sources, so what you said won't fix my issue 😅 so I'll wait until it's fixed ^^

**Comment by SkytAsul** [comment] 2019-12-26 16:54
Still happens with 1.15.1 server and enigma v0.14.3.146 :/ do you think this issue will be fixed?

**Comment by almic** [comment] 2019-12-26 17:45
I'm not an expert but I assume there's some funky stuff that Mojang did in a class file which results in a syntax error (but actually still executes fine in game). If we could find which class file has this problem and remove it, I'm sure the rest of the jar will be loaded just fine. We'll just be missing a single class file that might not even be very important.

**Comment by LaserSlimeHD** [comment] 2020-02-05 18:09
Please fix this! I want to decompile the server!

**Comment by liach** [comment] 2020-02-05 18:21
I actually don't know it this is an asm or proguard or enigma problem... need to check

**Comment by NickAcPT** [comment] 2020-02-05 22:06
I'm also facing this problem. Tried importing the 1.15.2 server jar and it happened.
I tried changing the ASM version to `1.7.1`, to no avail.

**Comment by SamB440** [comment] 2020-02-09 17:51
Also having this issue with the 1.16 server snapshot jar;

`java.lang.Error: java.lang.RuntimeException: org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 117: sizes don't match
	at cuchaz.enigma.gui.dialog.ProgressDialog.lambda$runOffThread$0(ProgressDialog.java:70)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 117: sizes don't match
	at cuchaz.enigma.analysis.index.IndexReferenceVisitor.lambda$visitMethod$0(IndexReferenceVisitor.java:49)
	at cuchaz.enigma.analysis.MethodNodeWithAction.visitEnd(MethodNodeWithAction.java:17)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1287)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:688)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
	at cuchaz.enigma.analysis.ClassCache.visit(ClassCache.java:108)
	at cuchaz.enigma.analysis.index.JarIndex.indexJar(JarIndex.java:67)
	at cuchaz.enigma.analysis.ClassCache.index(ClassCache.java:123)
	at cuchaz.enigma.Enigma.openJar(Enigma.java:55)
	at cuchaz.enigma.gui.GuiController.lambda$openJar$1(GuiController.java:90)
	at cuchaz.enigma.gui.dialog.ProgressDialog.lambda$runOffThread$0(ProgressDialog.java:66)
	... 1 more
Caused by: org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 117: sizes don't match
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:295)
	at cuchaz.enigma.analysis.index.IndexReferenceVisitor.lambda$visitMethod$0(IndexReferenceVisitor.java:47)
	... 11 more
Caused by: java.lang.IllegalStateException: sizes don't match
	at cuchaz.enigma.analysis.InterpreterPair.pair(InterpreterPair.java:100)
	at cuchaz.enigma.analysis.InterpreterPair.merge(InterpreterPair.java:88)
	at cuchaz.enigma.analysis.InterpreterPair.merge(InterpreterPair.java:14)
	at org.objectweb.asm.tree.analysis.Frame.merge(Frame.java:676)
	at org.objectweb.asm.tree.analysis.Analyzer.merge(Analyzer.java:541)
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:267)
	... 12 more
`

**Comment by liach** [comment] 2020-02-09 18:09
I think this issue is caused by some classes present in the shipped libraries (inner class without outer class)

**Comment by 05b001** [comment] 2020-02-27 18:59
I'm currently having this issue with all of the server jars above 1.15.1, till it's fixed use MC-Remapper.

**Comment by 05b001** [comment] 2020-02-27 22:12
Version 0.14.2.134 of enigma currently doesn't have this bug, here's the download link, https://maven.fabricmc.net/cuchaz/enigma/0.14.2.134/

**Comment by liach** [comment] 2020-02-28 04:10
So it is somewhere between 6a7192e18336e933f77d2e16f8f0e8eb114949e3 and 0e67256a2a66b2d0a0c6b3491ab2db63884bd55f, hmm

**Comment by Runemoro** [comment] 2020-02-28 04:15
It was caused by https://github.com/FabricMC/Enigma/pull/157. I'll look at it and fix it this weekend.

**Comment by SkytAsul** [comment] 2020-03-11 17:20
Unfortunately, it stills happen with the latest version, even when using CFR :/
This is the stacktrace with Procyon:
```
java.lang.Error: java.lang.RuntimeException: org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 117: sizes don't match
	at cuchaz.enigma.gui.dialog.ProgressDialog.lambda$0(ProgressDialog.java:71)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 117: sizes don't match
	at cuchaz.enigma.analysis.index.IndexReferenceVisitor.lambda$0(IndexReferenceVisitor.java:49)
	at cuchaz.enigma.analysis.MethodNodeWithAction.visitEnd(MethodNodeWithAction.java:17)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1287)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:688)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
	at cuchaz.enigma.analysis.ClassCache.visit(ClassCache.java:108)
	at cuchaz.enigma.analysis.index.JarIndex.indexJar(JarIndex.java:69)
	at cuchaz.enigma.analysis.ClassCache.index(ClassCache.java:123)
	at cuchaz.enigma.Enigma.openJar(Enigma.java:55)
	at cuchaz.enigma.gui.GuiController.lambda$0(GuiController.java:97)
	at cuchaz.enigma.gui.dialog.ProgressDialog.lambda$0(ProgressDialog.java:67)
	... 1 more
Caused by: org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 117: sizes don't match
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:295)
	at cuchaz.enigma.analysis.index.IndexReferenceVisitor.lambda$0(IndexReferenceVisitor.java:47)
	... 11 more
Caused by: java.lang.IllegalStateException: sizes don't match
	at cuchaz.enigma.analysis.InterpreterPair.pair(InterpreterPair.java:100)
	at cuchaz.enigma.analysis.InterpreterPair.merge(InterpreterPair.java:88)
	at cuchaz.enigma.analysis.InterpreterPair.merge(InterpreterPair.java:1)
	at org.objectweb.asm.tree.analysis.Frame.merge(Frame.java:676)
	at org.objectweb.asm.tree.analysis.Analyzer.merge(Analyzer.java:541)
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:267)
	... 12 more
```
This seems to be like a pain in the ass to fix :(

**Comment by NickAcPT** [comment] 2020-04-05 22:14
Just wondering, has there been any progress on this?

**Closed** 2020-04-18 13:25 UTC
Labels: bug

**Comment by LiamTormey** [comment] 2020-06-15 13:26
Was this issue resolved, because im still getting this bug.

**Comment by liach** [comment] 2020-06-15 13:29
make sure you test with enigma on maven than that from gradlew yarn.
