### ISSUE TITLE
crashed when export soures

### ISSUE THREAD

**Issue by axcsds** [FabricMC/Enigma#292] opened 2020-07-10 19:19 UTC
crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources

**Comment by Earthcomputer** [comment] 2020-07-10 19:20
What was that? I didn't quite hear you

**Comment by axcsds** [comment] 2020-07-10 19:22
crashed when export sources

**Comment by Devan-Kerman** [comment] 2020-07-10 19:22
ah

**Comment by axcsds** [comment] 2020-07-10 19:22
in 1.16.1
progurad mapping

**Comment by axcsds** [comment] 2020-07-10 19:22
crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources

**Comment by axcsds** [comment] 2020-07-10 19:23
crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources  crashed when export sources

**Comment by axcsds** [comment] 2020-07-10 19:24
using Procyon using Procyon using Procyon using Procyon using Procyon using Procyon using Procyon using Procyon using Procyon using Procyon using Procyon using Procyon using Procyon using Procyon using Procyon THEN crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sourcescrashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources crashed when export sources

**Comment by Earthcomputer** [comment] 2020-07-10 19:29
It's very windy outside - I'm not sure if I heard you properly over the wind - but I think I could just about make out that Enigma crashes when using proguard to export sources?
In that case, it's a duplicate of #279

**Closed** 2020-07-10 19:33 UTC
