### ISSUE TITLE
Can't open jar

### ISSUE THREAD

**Issue by aianlinb** [FabricMC/Enigma#194] opened 2020-02-23 03:09 UTC
java.lang.Error: java.lang.RuntimeException: org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 117: sizes don't match
	at cuchaz.enigma.gui.dialog.ProgressDialog.lambda$runOffThread$0(ProgressDialog.java:70)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.RuntimeException: org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 117: sizes don't match
	at cuchaz.enigma.analysis.index.IndexReferenceVisitor.lambda$visitMethod$0(IndexReferenceVisitor.java:49)
	at cuchaz.enigma.analysis.MethodNodeWithAction.visitEnd(MethodNodeWithAction.java:17)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1287)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:688)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
	at cuchaz.enigma.analysis.ClassCache.visit(ClassCache.java:108)
	at cuchaz.enigma.analysis.index.JarIndex.indexJar(JarIndex.java:67)
	at cuchaz.enigma.analysis.ClassCache.index(ClassCache.java:123)
	at cuchaz.enigma.Enigma.openJar(Enigma.java:55)
	at cuchaz.enigma.gui.GuiController.lambda$openJar$1(GuiController.java:90)
	at cuchaz.enigma.gui.dialog.ProgressDialog.lambda$runOffThread$0(ProgressDialog.java:66)
	... 1 more
Caused by: org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 117: sizes don't match
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:295)
	at cuchaz.enigma.analysis.index.IndexReferenceVisitor.lambda$visitMethod$0(IndexReferenceVisitor.java:47)
	... 11 more
Caused by: java.lang.IllegalStateException: sizes don't match
	at cuchaz.enigma.analysis.InterpreterPair.pair(InterpreterPair.java:100)
	at cuchaz.enigma.analysis.InterpreterPair.merge(InterpreterPair.java:88)
	at cuchaz.enigma.analysis.InterpreterPair.merge(InterpreterPair.java:14)
	at org.objectweb.asm.tree.analysis.Frame.merge(Frame.java:676)
	at org.objectweb.asm.tree.analysis.Analyzer.merge(Analyzer.java:541)
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:267)
	... 12 more

**Comment by liach** [comment] 2020-02-23 03:43
Duplicate of #179

**Closed** 2020-02-23 04:20 UTC
