### ISSUE TITLE
Exporting source does nothing

### ISSUE THREAD

**Issue by skyrocketc** [FabricMC/Enigma#526] opened 2023-07-13 13:51 UTC
When i try to export the deobfuscated source, it does nothing.

**Comment by Guigui220D** [comment] 2023-12-30 10:04
#494

**Comment by Enaium** [comment] 2024-01-24 17:49
[enigma-swing-2.3.3-all-fix-export-source.zip](https://github.com/FabricMC/Enigma/files/14041936/enigma-swing-2.3.3-all-fix-export-source.zip)

**Comment by NebelNidas** [comment] 2024-04-07 11:13
Duplicate of #487.

**Closed by NebelNidas** 2024-04-07 11:13 UTC
